// AI briefing API route — generates operator briefing from conjunction data.

import { NextRequest, NextResponse } from 'next/server'
import { chatText } from '@/lib/ai'
import fs from 'fs'
import path from 'path'

export async function GET(req: NextRequest) {
  try {
    // Load conjunction data generated by screen.js
    const dataPath = path.join(process.cwd(), 'data', 'conjunctions.json')
    if (!fs.existsSync(dataPath)) {
      return NextResponse.json({ error: 'No conjunction data found. Run: npm run screen' }, { status: 404 })
    }

    const conjData = JSON.parse(fs.readFileSync(dataPath, 'utf8'))

    if (!conjData.events || conjData.events.length === 0) {
      return NextResponse.json({
        briefing: `No close approaches detected for ${conjData.primary} within ${conjData.screen_km} km over the next ${conjData.window_hours} hours. Orbital corridor is clear.`,
        risk: 'CLEAR',
        events: []
      })
    }

    // Build AI prompt with real conjunction data
    const system = `You are an orbital collision assessment AI briefing mission operators on conjunction events.

Your task: analyze the provided close approach data and generate a concise operator briefing.

Output format (plain text, no JSON):
1. RISK ASSESSMENT: [CRITICAL/HIGH/MODERATE/LOW] - one word + short reason
2. PRIMARY ASSET: name + altitude
3. TOP THREATS: list 2-3 closest approaches with object name, miss distance, relative velocity, TCA
4. CONTEXT: explain what debris cloud(s) these are from (e.g. 2009 Iridium-Cosmos collision)
5. RECOMMENDATION: maneuver options (e.g. "consider radial boost +X m/s" or "monitor, no action yet")

Keep it concise (under 300 words), grounded in the data, and actionable. Do NOT invent collision probabilities — the TLE data lacks covariance.`

    const topEvents = conjData.events.slice(0, 5)
    const user = `Primary: ${conjData.primary}
Window: ${conjData.window_hours} hours
Screen threshold: ${conjData.screen_km} km
Total approaches found: ${conjData.events.length}

Top ${topEvents.length} closest approaches:
${topEvents.map((e: any, i: number) =>
  `${i + 1}. ${e.secondary} - miss ${e.missKm.toFixed(2)} km, rel speed ${e.relKmS.toFixed(2)} km/s @ ${e.tca}`
).join('\n')}

Generate operator briefing.`

    const briefing = await chatText({ system, user, maxTokens: 2048 })

    // Determine risk level from miss distances
    const closest = conjData.events[0].missKm
    let risk = 'LOW'
    if (closest < 5) risk = 'CRITICAL'
    else if (closest < 10) risk = 'HIGH'
    else if (closest < 20) risk = 'MODERATE'

    return NextResponse.json({
      briefing,
      risk,
      events: conjData.events,
      primary: conjData.primary,
      window_hours: conjData.window_hours,
    })
  } catch (error: any) {
    console.error('Briefing generation failed:', error)
    return NextResponse.json({ error: error.message || 'Briefing generation failed' }, { status: 500 })
  }
}
